Install MPI from apt or source in CI.
For MPICH, this only works with >= 3.3 due to package naming / gcc incompatibility.

In the future we could adjust the matrix such that MPI is part of the cudacxx matrix component, but this would become much more verbose.

diff --git a/.github/workflows/MPI.yml b/.github/workflows/MPI.yml
--- a/.github/workflows/MPI.yml
+++ b/.github/workflows/MPI.yml
@@ -45,14 +45,28 @@ jobs:
         python:
           - "3.8"
         mpi:
-          - lib: "libmpich-dev"
+          - lib: "openmpi"
+            version: "apt"
+          - lib: "openmpi"
+            version: "4.1.6"
+          - lib: "openmpi"
+            version: "4.0.0"
+          - lib: "openmpi"
+            version: "3.0.0"
+          - lib: "openmpi"
+            version: "2.0.0"
+          - lib: "openmpi"
+            version: "1.10.7"
+          - lib: "mpich"
+            version: "apt"
+          - lib: "mpich"
+            version: "4.1.2"
+          - lib: "mpich"
+            version: "4.0"
+          - lib: "mpich"
+            version: "3.4.3"
+          - lib: "mpich"
             version: "3.3"
-          - lib: "libmpich-dev"
-            version: "4.0.2"
-          - lib: "libopenmpi-dev"
-            version: "4.0.3"
-          - lib: "libopenmpi-dev"
-            version: "4.1.5"
         config:
           - name: "Release"
             config: "Release"
@@ -100,9 +114,57 @@ jobs:
         echo "CXX=/usr/bin/g++-${gcc_version}" >> $GITHUB_ENV
         echo "CUDAHOSTCXX=/usr/bin/g++-${gcc_version}" >> $GITHUB_ENV
     
-    - name: Install MPI
+    - name: Install MPI from apt
+      if: ${{ env.MPI_VERSION == 'apt' }}
+      working-directory: ${{ runner.temp }}
       run: |
-        sudo apt-get install -y ${MPI_LIB}=${MPI_VERSION}
+        sudo apt-get install lib${{ env.MPI_LIB }}-dev
+
+    - name: Install OpenMPI from source
+      if: ${{ env.MPI_VERSION != 'apt' && env.MPI_LIB == 'openmpi' }}
+      working-directory: ${{ runner.temp }}
+      run: |
+        # Note: using download.open-mpi.org as gh tags aren't pre configured
+        MPI_VERISON_MAJOR_MINOR=$(cut -d '.' -f 1,2 <<< "${{ env.MPI_VERSION}}")
+        echo "https://download.open-mpi.org/release/open-mpi/v${MPI_VERISON_MAJOR_MINOR}/openmpi-${{ env.MPI_VERSION}}.tar.gz"
+        wget -q https://download.open-mpi.org/release/open-mpi/v${MPI_VERISON_MAJOR_MINOR}/openmpi-${{ env.MPI_VERSION}}.tar.gz --output-document openmpi-${{ env.MPI_VERSION }}.tar.gz || (echo "An Error occurred while downloading OpenMPI '${{ env.MPI_VERSION }}'. Is it a valid version of OpenMPI?" && exit 1)
+        tar -zxvf openmpi-${{ env.MPI_VERSION }}.tar.gz
+        cd openmpi-${{ env.MPI_VERSION}}
+        ./configure --prefix="${{ runner.temp }}/mpi"
+        make -j `nproc`
+        make install -j `nproc`
+        echo "${{ runner.temp }}/mpi/bin" >> $GITHUB_PATH
+        echo "LD_LIBRARY_PATH=${{ runner.temp }}/mpi/lib:${LD_LIBRARY_PATH}" >> $GITHUB_ENV
+        echo "LD_RUN_PATH=${{ runner.temp }}/mpi/lib:${LD_RUN_PATH}" >> $GITHUB_ENV
+
+    # This will only work for mpich >= 3.3:
+    #   3.0-3.2 doesn't appear compatible with default gcc in 22.04. 
+    #   1.x is named mpich2 so requires handling differently
+    # Uses the ch3 interface, as ch4 isn't available pre 3.4, but one must be specified for some versions
+    - name: Install MPICH from source
+      if: ${{ env.MPI_VERSION != 'apt' && env.MPI_LIB == 'mpich' }}
+      working-directory: ${{ runner.temp }}
+      run: |
+        MPI_MAJOR=$(cut -d '.' -f 1 <<< "${{ env.MPI_VERSION}}")
+        MPI_MINOR=$(cut -d '.' -f 2 <<< "${{ env.MPI_VERSION}}")
+        [[ ${MPI_MAJOR} < 3 ]] && echo "MPICH must be >= 3.0" && exit 1
+        echo "https://www.mpich.org/static/downloads/${{ env.MPI_VERSION }}/mpich-${{ env.MPI_VERSION}}.tar.gz"
+        wget -q https://www.mpich.org/static/downloads/${{ env.MPI_VERSION }}/mpich-${{ env.MPI_VERSION}}.tar.gz --output-document mpich-${{ env.MPI_VERSION }}.tar.gz || (echo "An Error occurred while downloading MPICH '${{ env.MPI_VERSION }}'. Is it a valid version of MPICH?" && exit 1)
+        tar -zxvf mpich-${{ env.MPI_VERSION }}.tar.gz
+        cd mpich-${{ env.MPI_VERSION}}
+        DISABLE_FORTRAN_FLAGS=""
+        if (( ${MPI_MAJOR} >= 4 )) || ( ((${MPI_MAJOR} >= 3)) && ((${MPI_MINOR} >= 2)) ); then
+            # MPICH >= 3.2 has --disable-fortran
+            DISABLE_FORTRAN_FLAGS="--disable-fortran" 
+        else
+            DISABLE_FORTRAN_FLAGS="--disable-f77 --disable-fc"
+        fi
+        ./configure --prefix="${{ runner.temp }}/mpi" --with-device=ch3 ${DISABLE_FORTRAN_FLAGS}
+        make -j `nproc`
+        make install -j `nproc`
+        echo "${{ runner.temp }}/mpi/bin" >> $GITHUB_PATH
+        echo "LD_LIBRARY_PATH=${{ runner.temp }}/mpi/lib:${LD_LIBRARY_PATH}" >> $GITHUB_ENV
+        echo "LD_RUN_PATH=${{ runner.temp }}/mpi/lib:${LD_RUN_PATH}" >> $GITHUB_ENV
     
     - name: Select Python
       if: ${{ env.PYTHON != '' && env.FLAMEGPU_BUILD_PYTHON == 'ON' }} 
